# 网站的基础URL，这是你的网站将要部署的地址
baseURL = "https://R0B0Tao.github.io"

# 网站的语言代码
languageCode = "zh-cn"

# 网站的标题，会显示在浏览器标签页和主题中
title = "R0B0Tao"

# 使用的主题名称，必须与主题文件夹名称一致
theme = "Less"

# 可自定义参数
[params]

#个人简介
bio = "在做实验和扣代码之间选择了摸鱼。"

# 社交媒体链接
[[params.social]]
name = "GitHub"
url = "https://github.com/R0B0Tao"
icon = "github"

[[params.social]]
name = "Email"
url = "Marceline.Tao@outlook.com"
icon = "mail"

[[params.social]]
name = "RSS"
url = "/index.xml"
icon = "rss"

[taxonomies]
category = "categories"

[params.giscus]
repo = "your-username/your-repo"
repoID = "Your-Repo-ID"
category = "Announcements"
categoryID = "Your-Category-ID"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "noborder_gray"
lang = "zh-CN"
